// lib/staff.js
//
// MFWA staff directory, as published on the live site (Sept 2026): names,
// positions, portraits and biographies were read from
// https://mfwa.org/about-us/our-staff/ and each member's /team/<slug>/
// page. The live WordPress "team" post type isn't exposed through the REST
// API, which is why this lives as local data for now — once it is (or an
// ACF endpoint is added), getStaffPage() in lib/content.js is the only
// place that needs to switch to a fetch; the shape below is what the UI
// consumes.
//
// Portraits are served straight from the WordPress media library:
//   thumb — the 570×696 crop the live directory uses (grid cards)
//   photo — the larger original used on each member's page (modal)
// `team` groups people for the directory filter; it is derived from each
// person's position and biography, not a field on the live site.

const U = "https://mfwa.org/wp-content/uploads/";

export const STAFF_TEAMS = [
  { id: "all", label: "Everyone" },
  { id: "leadership", label: "Leadership" },
  { id: "programmes", label: "Programmes" },
  { id: "journalism", label: "The Fourth Estate" },
  { id: "communications", label: "Communications" },
  { id: "operations", label: "Finance & operations" },
];

export const STAFF = [
  {
    slug: "abigail-larbi-odei",
    name: "Abigail Larbi Odei",
    role: "Senior Director / Head of Operations",
    team: "leadership",
    thumb: `${U}2025/07/Untitled-570x696.jpg`,
    photo: `${U}2025/07/Untitled-840x1150.jpg`,
    bio: [
      "Abigail Larbi is the Senior Director and Head of Operations at the MFWA, leading the strengthening of the organisation’s systems, policies, human resource and outreach efforts.",
      "She joined the organisation in 2011. Between 2011 and 2024, she led the MFWA’s Media and Governance Programme where she engaged in advocacy, fundraising, grant management and stakeholder analysis/engagement. Abigail curated participatory and deliberative processes/platforms that promoted citizens-authorities engagement, promoting civic participation and democratic governance in 40 districts in Ghana.",
      "She managed several projects including the Media for Accountable local governance project, Promoting Women’s Voices in Public Discourse, and Equal Voices in Media; the MFWA’s flagship language Monitoring project and Countering Mis/disinformation. She facilitated the training of many journalists on diverse themes; and extended financial support to several independent journalism newsrooms across West Africa.",
      "She was instrumental in the setting up of Fact-Check Ghana and the commencement of the annual West Africa Media Excellence Conference and Awards (WAMECA). She also coordinated engagements with several reputable funders including, OSIWA, Hewlett Foundation, UNDP, DW Akademie, US Embassy, Ghana and FCDO, Wikimedia Foundation, EU Delegation Guinea Bissau.",
      "Before joining the MFWA, Abigail worked at the Ghana Broadcasting Corporation (GBC) Radio Newsroom as an Editor, News Anchor and Current Affairs show host and a host of the Morning Magazine Show “The Breakfast show” on Ghana Television.",
      "Abigail has an MA in International Relations and Democratic Politics from the University of Westminster, UK, an MA in Communication Studies and a BA in English and Linguistics from the University of Ghana. She is a Chevening Scholar and a Mandela Washington Fellow.",
    ],
  },
  {
    slug: "adizatu-moro-maiga",
    name: "Adizatu Moro Maiga",
    role: "Programme Manager",
    team: "programmes",
    thumb: `${U}2025/07/adiza-570x696.jpg`,
    photo: `${U}2025/07/adiza-840x1219.jpg`,
    bio: [
      "Ms. Adizatu Moro Maiga is a Programme Manager for the Media for Democracy and Good Governance Programme, where she oversees strategic planning, coordination, and implementation of programme activities. She manages daily project operations, ensuring effective execution, stakeholder engagement, and alignment with organisational goals.",
      "In the past, Ms. Maiga has managed the MFWA’s Sustainable Development Goals (SDGs) project, providing overall leadership in the development of concepts, strategic initiatives, and capacity-building programmes for journalists and key stakeholders. In this role, she drove the design and delivery of innovative interventions that strengthen media engagement with the SDGs and promoted accountability in sustainable development processes.",
      "Before joining the MFWA, Ms. Maiga gained extensive public sector experience working with the Ministry of Foreign Affairs and Regional Integration, the Ministry of Employment and Social Welfare, and the Accra Metropolitan Assembly. She has also contributed to social protection initiatives through her volunteer work, including the Livelihood Empowerment Against Poverty (LEAP) programme.",
      "Ms. Maiga holds a Master’s degree in Regional Integration from the Pan African University of Governance, Humanities and Social Sciences (PAUGHSS), Cameroun, and a Bachelor’s degree in Sociology with Philosophy from the University of Ghana. She has earned several professional certifications, including a Certificate in Child Labour and Trafficking from the International Training Centre of the International Labour Organization (ITC/ILO), Italy.",
    ],
  },
  {
    slug: "alice-assibuaba-assibu",
    name: "Alice Assibuaba Assibu",
    role: "Finance Associate",
    team: "operations",
    thumb: `${U}2026/03/Alice-570x696.png`,
    photo: `${U}2026/03/Alice-840x1211.png`,
    bio: [
      "Alice Assibuaba Assibu is a Finance Associate at the Media Foundation for West Africa, where she supports financial reporting, budgeting, compliance and strengthening of internal control systems to ensure effective resource management. She has over 5 years’ experience in Accounting and Finance.",
      "She is a member of the institute of Chartered Accountants, Ghana (ICAG) and also holds a Bachelor of Science in Banking and Finance from the University of Professional Studies, Accra.",
    ],
  },
  {
    slug: "clement-kumsah",
    name: "Clement E. Kumsah",
    role: "Investigative Journalist",
    team: "journalism",
    thumb: `${U}2025/07/PILOLO-570x696.jpg`,
    photo: `${U}2025/07/PILOLO-840x1125.jpg`,
    bio: [
      "Clement Edward Kumsah is an investigative/photo journalist with The Fourth Estate, a non-profit public interest investigative journalism project of the MFWA.",
      "He documents governance, public accountability, and civic action while leading video production for investigative documentaries.",
      "In addition to frontline reporting, he oversees digital publishing, SEO strategy, and audience analytics, helping to strengthen the newsroom’s online reach and impact.",
      "Clement is passionate about strengthening accountability journalism in Africa and exploring how artificial intelligence can be used responsibly to support investigative reporting and digital innovation.",
    ],
  },
  {
    slug: "daisy-prempeh",
    name: "Daisy Prempeh",
    role: "Administrative Officer",
    team: "operations",
    thumb: `${U}2026/02/daisy-570x696.png`,
    photo: `${U}2026/02/daisy-840x1260.png`,
    bio: [
      "Daisy Prempeh is the Administrative Officer of the Media Foundation for West Africa (MFWA). She is a Bilingual Secretary and joined the organisation in February 2000.",
      "She was educated at the Ghana Institute of Languages, where she studied Bilingual Secretaryship.",
      "Although largely in charge of administrative duties, Daisy over the years has supported and managed a few projects at the MFWA. She coordinated the Programme for African Investigative Reporting (PAIR) project, jointly initiated in 2009 by the Danish Association for Investigative Reporting (FUJ) and the International Media Support (IMS) both in Copenhagen, Denmark in collaboration with Media Foundation for West Africa (MFWA) serving as a regional partner of the project.",
      "She has also coordinated the MFWA/EU-Guinea Bissau project titled Promoting Media Freedom and Access to Quality Information in Guinea Bissau.",
    ],
  },
  {
    slug: "daniel-kwame-ampofo-adjei",
    name: "Daniel Kwame Ampofo Adjei, PhD., PMP®",
    role: "Programme Manager",
    team: "programmes",
    thumb: `${U}2025/07/DKAA_Small-570x696.jpg`,
    photo: `${U}2025/07/DKAA_Small-840x810.jpg`,
    bio: [
      "Daniel leads organisation-wide efforts to strengthen Monitoring, Evaluation, Accountability and Learning (MEAL) systems, align programmes with strategic objectives, and ensure evidence-based decision-making, accountability, and compliance across diverse multi-donor portfolios. He has experience in project design and MEAL, particularly in results frameworks, indicators, data systems, and learning for adaptive management and institutional effectiveness.",
      "He led the development of the MEAL components of Ghana’s National Risk Communication and Community Engagement Strategy for the COVID-19 response and contributed to the design and implementation of communication strategies for the STAR-Ghana (Phase II) Programme and its successor, the STAR-Ghana Foundation.",
      "He has worked closely with key government institutions (Ghana Education Service, Ministry of Education, Ghana Health Service, Ministry of Health etc.) supporting evaluations and learning initiatives that document social, behavioural, and policy impacts across individuals, institutions, and communities.",
      "He has also facilitated media and citizen-engagement initiatives, equipping marginalised communities in Ghana, Nigeria, and Zimbabwe to generate evidence and advocate for their needs through mobile-enabled community reporting.",
      "Prior to joining MFWA, Daniel served in MEAL- and systems-oriented roles with On Our Radar (FCDO-funded ECID Programme), Christian Aid International (STAR-Ghana Phase II, Hopeline Institute, and the Noguchi Memorial Institute for Medical Research (UKRI funded project).",
      "He has assisted in teaching and research at the Department of Communication Studies, University of Ghana. He has also consulted for the Ghana Grains Council, FHI 360 Ghana, the John Agyekum Kufuor Foundation, and Farm Radio International.",
      "Daniel is a PMI-certified Project Management Professional (PMP®) and holds a Ph.D. in Communication Studies from the University of Ghana. He also holds a Master of Philosophy (MPhil) in NGO Studies and Community Development and a Bachelor of Science (BSc) in Agriculture, both from the University of Cape Coast, Ghana.",
      "His research focuses on communication and public policy, digital public health, mis/disinformation, and inclusive civic technologies. His scholarly work has been published in outlets including BMC Public Health; Journal of Communication in Healthcare; Public Relations Review; Ghana Medical Journal; and Routledge-edited volumes.",
    ],
  },
  {
    slug: "delali-dessouassi",
    name: "Delali J.D. Dessouassi",
    role: "Programme Associate",
    team: "programmes",
    thumb: `${U}2025/07/dela-ag-570x696.jpg`,
    photo: `${U}2025/07/dela-ag-840x741.jpg`,
    bio: [
      "Delali JD Dessouassi serves as Programme Associate and Multilingual Translator with the Media Foundation for West Africa (MFWA), where he contributes to advancing press freedom, democratic governance, and media development across West Africa.",
      "He also contributes to analytical reports, alerts, and special publications on freedom of expression, and supports engagement with journalists, governments, and regional stakeholders. With a background in French–English–Portuguese translation and over five years of professional experience, Delali has worked in diverse and multicultural environments.",
      "He has coordinated an EU-funded initiative in Guinea-Bissau aimed at promoting and protecting democracy by safeguarding freedom of opinion and expression and countering mis/disinformation.",
      "Passionate about fostering dialogue across cultures, Delali remains committed to strengthening democratic values and protecting media freedom in West Africa.",
    ],
  },
  {
    slug: "diane-rachelle-sylvia-badolo",
    name: "Diane Rachelle Sylvia Badolo",
    role: "Programme Assistant",
    team: "programmes",
    thumb: `${U}2026/03/Untitled-4-1-570x696.jpg`,
    photo: `${U}2026/03/Untitled-4-1-840x1122.jpg`,
    bio: [
      "Diane Rachelle Sylvia Badolo is a Programme Assistant at the Media Foundation for West Africa (MFWA), where she supports regional initiatives on freedom of expression, journalists’ safety across West Africa. She contributes to monitoring and documenting press freedom violations, coordinating capacity-building workshops, and engaging with media professionals, regulators, security agencies, and civil society actors.",
      "She holds a Master’s degree in International Business Law from Université Aube Nouvelle in Burkina Faso, equipping her with strong legal expertise to analyse media laws and human rights frameworks and support advocacy efforts that promote democratic governance and accountability.",
      "Diane also has experience in communications and has supported initiatives focused on children’s rights, gender equality, and the prevention of violence against women.",
    ],
  },
  {
    slug: "dora-b-mawutor",
    name: "Dora Boamah Mawutor",
    role: "Senior Director / Head of Programmes",
    team: "leadership",
    thumb: `${U}2025/07/DORA-B.-1-1-570x696.jpg`,
    photo: `${U}2025/07/DORA-B.-1-1-840x1260.jpg`,
    bio: [
      "Dora B. Mawutor is the Director of the Freedom of Expression & Digital Rights Programme at the Media Foundation for West Africa.",
      "She joined the MFWA in 2012. Between 2012 and 2014, she led some of the organisation’s influential media research activities including Language Monitoring on Radio during the 2012 General Elections and the adjudication of the 2012 Elections Petition; Monitoring of Women’s Participation in Public Discourse on Radio, and Media Ethics Monitoring.",
      "From 2014, Dora coordinated the organisation’s Internet freedom advocacy projects under the Freedom of Expression Programme and represented the organisation on a number of national, regional and international platforms on digital rights issues. She subsequently became the manager of the Freedom of Expression Programme in 2016 until late 2018 when she was asked to lead the newly created Institutional Development Programme.",
      "Before joining MFWA, Dora worked at Stratcomm Africa in Accra as a Senior Communications Officer; Seatec Telecoms Services Limited as a Project Coordinator and a Personal Assistant to the Managing Director; and the Adventist Development and Relief Agency (ADRA) as a National Service Person.",
      "Dora has a Master of Philosophy Degree in Communication Studies from the University of Ghana and a Bachelor of Arts Degree in Information Studies and French, also from the University of Ghana.",
    ],
  },
  {
    slug: "edmund-agyemang-boateng",
    name: "Edmund Agyemang Boateng",
    role: "Investigative Journalist",
    team: "journalism",
    thumb: `${U}2026/03/Edmund-570x696.jpg`,
    photo: `${U}2026/03/Edmund-840x1204.jpg`,
    bio: [
      "Edmund Agyemang Boateng is an investigative journalist with The Fourth Estate, the MFWA’s public interest journalism project. His investigations have uncovered the operations of unlicensed sachet water companies in Accra, suspected killings in police custody, illegal mining takeovers involving national security and an MP, misappropriated public funds, and election collation failures causing distrust and deaths.",
      "Working with colleagues, Boateng revealed how influential figures, including a former Chief of Staff’s son, held mining concessions on ravaged riverbanks despite bans, and exposed a failed $15.8 million Accra streetlighting project. In November 2025, he and a colleague were runners-up at the Africa Investigative Journalist Award.",
      "On May 2025, he won the Media Freedom Coalition’s Long Report award for the galamsey (illegal mining) exposé, amplifying the fight against illegal mining.",
    ],
  },
  {
    slug: "elijah-ago-acquaye",
    name: "Elijah Ago Acquaye",
    role: "Finance Officer",
    team: "operations",
    thumb: `${U}2025/07/Elijah-570x696.png`,
    photo: `${U}2025/07/Elijah-840x1260.png`,
    bio: [
      "Elijah Ago Acquaye is a Finance Officer at the Media Foundation for West Africa. He has over ten years of experience in accounting and finance.",
      "Before joining the MFWA, Elijah worked as the Senior Accounts Officer at African Towers Limited. He is a member of the Institute of Financial Accountants, United Kingdom and the Institute of Public Accountants, Australia.",
      "Elijah holds a Bachelor of Commerce in Accounting (BCom Accounting) degree from the University of Cape Coast and a Higher National Diploma (HND) Accounting option.",
    ],
  },
  {
    slug: "elizabeth-abena-egyin",
    name: "Elizabeth Abena Egyin",
    role: "Investigative Journalist",
    team: "journalism",
    thumb: `${U}2026/02/LIZZY-scaled-e1770378115203-570x696.png`,
    photo: `${U}2026/02/LIZZY-scaled-e1770378115203-840x955.png`,
    bio: [
      "Elizabeth Abena Egyin is an investigative journalist with The Fourth Estate, the MFWA’s investigative and accountability journalism project.",
      "Before joining the MFWA team in January 2025, she worked as a news reporter and a political show producer for Peace FM (Despite Media).",
      "Elizabeth has a Bachelor of Arts degree in Communication Studies from the University of Media, Arts, and Communication (UNIMAC-IJ). She majored in Public Relations.",
    ],
  },
  {
    slug: "enoch-sam",
    name: "Enoch Sam",
    role: "Programme Assistant",
    team: "communications",
    thumb: `${U}2026/03/SAM-570x696.jpg`,
    photo: `${U}2026/03/SAM-840x1145.jpg`,
    bio: [
      "Enoch Sam is a Programme Assistant in the MFWA’s Institutional Development programme. He is a member of the communications team responsible for photography, videography and video editing of all visual materials.",
      "Before joining Media Foundation for West Africa, he worked on several creative projects ranging from films, design and brand campaigns with notable brands like Fearnoman, Pan African Heritage World Museum and Dyson Energy.",
      "Enoch Sam studied Visual and Digital Communication at the African University of Communication and Business.",
    ],
  },
  {
    slug: "fatimata-mustapha",
    name: "Fatimata Mustapha",
    role: "Programme Assistant",
    team: "programmes",
    thumb: `${U}2026/03/fati-2-570x696.png`,
    photo: `${U}2026/03/fati-2-840x1212.png`,
    bio: [
      "Fatimata Mustapha is a Programme Assistant at the MFWA, where she supports the implementation and coordination of projects under the Media for Democracy and Good Governance Programme. She holds a Bachelor of Arts Degree in Geography and Resource Development with Sociology from the University of Ghana.",
    ],
  },
  {
    slug: "frank-foli",
    name: "Frank Foli",
    role: "Security Officer",
    team: "operations",
    thumb: `${U}2024/08/frank-foli.png`,
    photo: `${U}2024/08/frank-foli.png`,
    bio: ["Frank Foli is the Security Officer of the organisation."],
  },
  {
    slug: "james-abbey",
    name: "James Abbey",
    role: "Video Editor",
    team: "communications",
    thumb: `${U}2026/03/james-570x696.jpg`,
    photo: `${U}2026/03/james-840x1163.jpg`,
    bio: [
      "James Abbey is a documentary video editor, motion graphics designer, and visual storyteller with the Media Foundation for West Africa (MFWA). He contributes to the organisation’s multimedia and documentary storytelling efforts, supporting investigative journalism, accountability initiatives, and human rights advocacy by translating complex social and governance issues into engaging visual narratives.",
      "Prior to joining MFWA in August 2025, James worked with Multimedia Group Limited (MGL) as a documentary video editor for JoyNews and JoyPrime. During his time at MGL, he was involved in the production of news features, long-form documentaries, and visual explainers, gaining valuable experience in broadcast journalism and fast-paced newsroom environments.",
      "James holds a Diploma Certificate in Video Editing, Graphic Design from Creativeland School of Film and Media Art.",
    ],
  },
  {
    slug: "josephine-badu-nyarko",
    name: "Josephine Badu-Nyarko",
    role: "Programme Assistant",
    team: "programmes",
    thumb: `${U}2026/03/Josephine-570x696.jpg`,
    photo: `${U}2026/03/Josephine-840x1176.jpg`,
    bio: [
      "Josephine Badu-Nyarko is a Programme Assistant at the Media Foundation for West Africa, where she supports the implementation of initiatives under the Media for Democracy and Good Governance Programme.",
      "With a background in journalism and communications, Josephine brings a strong blend of journalism and programme coordination to her role. She leads the coordination of the Next Generation Investigative Journalism (NGIJ) Fellowship, overseeing recruitment, training logistics, stakeholder engagement, and learning visits. She also supports monitoring and evaluation processes, coordinating workshops and forums, and produces web and media content that highlights the impact of the Foundation’s work.",
      "Prior to her current role, Josephine worked as a journalist with MFWA’s investigative and fact-checking platforms, including The Fourth Estate and Fact-Check Ghana, where she produced stories focused on governance, transparency, and anti-corruption. Her earlier experience includes serving as a Communications Assistant at MFWA and as an Administrative Assistant at the University of Ghana’s Public Affairs Directorate.",
      "Josephine holds a Bachelor of Arts in Communication Studies (Journalism option) from the University of Media, Arts and Communication and is an alumna of the Next Generation Investigative Journalism Fellowship.",
    ],
  },
  {
    slug: "kojo-impraim",
    name: "Kojo Impraim, PhD",
    role: "Programme Director",
    team: "leadership",
    thumb: `${U}2025/07/kojo-scaled-e1770376770191-570x696.png`,
    photo: `${U}2025/07/kojo-scaled-e1770376770191-840x840.png`,
    bio: [
      "Kojo Impraim (PhD) is the Director of Media for Peace and Sustainable Development Programme at the Media Foundation for West Africa. Prior to his appointment at the Foundation, Kojo was the Deputy Director in charge of research, monitoring and evaluation at the Ghana National Peace Council.",
      "He has also previously served as Project Director at Sera Matrix, Chief Operating Officer at the Africa Worldview Limited, and Programme Officer at the Institute of Democratic Governance. Kojo has also consulted on a number of projects for domestic and international organisations including the Ghana Broadcasting Corporation, Ghana Journalists Association, STAR-Ghana Foundation, Agence Francaise de Development (AFD), Newmont Ghana, Africa Centre for International Law and Accountability, and Human Rights Advocacy Centre. He has also managed several donor-driven projects in over 170 districts in Ghana.",
      "His competencies and interests span the areas of human rights and security, democratic policing, public safety, peacebuilding, human rights, media and communication, electoral politics, and preventing and countering violent extremism.",
      "Kojo holds a Doctor of Philosophy (PhD) in Politics and International Relations from the University of Cape Town, South Africa; M. Phil in Political Science from the University of Ghana; Bachelor of Arts in Political Science with Sociology (First Class Honors) also from the University of Ghana.",
      "He has also received training on Project Management from the University of La Verne, California; Conflict Analysis and Mediation from the Kofi Annan International Peacekeeping Training Centre in Ghana; and Master Class Security Governance from the National Security Institute in Ghana.",
    ],
  },
  {
    slug: "kwaku-krobea-asante",
    name: "Kwaku Krobea Asante",
    role: "Programme Manager",
    team: "programmes",
    thumb: `${U}2025/07/Untitled-2-1-570x696.jpg`,
    photo: `${U}2025/07/Untitled-2-1-840x1084.jpg`,
    bio: [
      "Kwaku Krobea Asante is the manager for the Independent Journalism Project. The project comprises The Fourth Estate, which is dedicated to investigative journalism, and Fact-Check Ghana, which focuses on countering disinformation.",
      "He was previously the lead of the communications team in charge of implementing the organisation’s communication strategy and ensuring the visibility of projects and their impact.",
      "Kwaku has led a number of key projects in the organisation including coordinating the communication and visibility of the European Union-funded Africa We Want Project, which was a consortium of 14 civil society organisations across eight African countries mobilizing support for the implementation of the African Charter on Democracy, Elections and Governance (ACDEG). He has previously also led the media ethics project that monitored professional standards among 26 media outlets during the 2020 elections in Ghana.",
      "Before joining the organisation, he worked as a research assistant on many communication research projects in Ghana. He holds a Master’s degree in Communication Studies and a Bachelor’s degree in Economics and Political Science, both from the University of Ghana.",
    ],
  },
  {
    slug: "margritta-amoaful-owusu",
    name: "Margritta Amoaful-Owusu",
    role: "Finance Manager",
    team: "operations",
    thumb: `${U}2025/07/Maggie-570x696.jpg`,
    photo: `${U}2025/07/Maggie-840x1153.jpg`,
    bio: [
      "Margritta Esi Amoaful-Owusu is the Director of Finance and Administration of the Media Foundation for West Africa (MFWA). She holds a Bachelor of Accounting (BA) degree from the Ghana Institute of Management and Public Administration (GIMPA) and a Higher National Diploma (HND) Accounting option.",
      "She previously worked with the Internal Revenue Service – Ghana, First Ghana Building Society and Hotel Catering and Tourism Training Institute. She is also a member of the Institute of Chartered Accountants Ghana. She has been working with the Media Foundation for West Africa since June 2001.",
    ],
  },
  {
    slug: "melvine-enzeng",
    name: "Melvine E.L. Enzeng",
    role: "Programme Assistant",
    team: "programmes",
    thumb: `${U}2025/07/melvin-570x696.png`,
    photo: `${U}2025/07/melvin-840x1180.png`,
    bio: [
      "Melvine is a Programme Assistant under the Freedom of Expression & Digital Rights Programme at the Media Foundation for West Africa.",
      "With a background in French–English translation, he contributes to in-depth analytical reports, rapid alerts, and special publications on freedom of expression in the region, while actively supporting the organisation’s engagements and advocacy in Francophone countries, facilitating engagement between journalists, government bodies, and regional stakeholders to promote a safer and more enabling environment for the media.",
      "With over four years of professional experience, Melvine combines linguistic expertise with practical knowledge of media and freedom of expression advocacy to support the organisation’s regional activities.",
      "Before joining the organisation, he worked as a freelance translator, French teacher, and movie dubbing artist.",
    ],
  },
  {
    slug: "meshack-odoi-yemoh",
    name: "Meshack Odoi Yemoh",
    role: "Programme Officer",
    team: "communications",
    thumb: `${U}2025/07/mESHACK-1-570x696.jpg`,
    photo: `${U}2025/07/mESHACK-1-840x1143.jpg`,
    bio: [
      "Meshack Odoi Yemoh is a Programme Officer under the Institutional Development Programme. He is a member of the communications team and is responsible for the production of digital communication materials. Before joining the organisation, he worked as a designer for Meqasa Housing Limited.",
      "Meshack holds a Bachelor of arts degree in Communication Design from the Kwame Nkrumah University of Science and Technology (KNUST), Ghana.",
    ],
  },
  {
    slug: "mia-ewagnignon",
    name: "Mia Ewagnignon",
    role: "Programme Assistant",
    team: "communications",
    thumb: `${U}2025/07/MIA-570x696.jpg`,
    photo: `${U}2025/07/MIA-840x1196.jpg`,
    bio: [
      "Mia Ewagnignon is a Programme Assistant for Communications under the Institutional Development Programme of the Media Foundation for West Africa (MFWA). Mia, who is from Benin, supports the organisation’s engagements and advocacy in Francophone countries. She graduated with honours from the University of Ghana with a Bachelor of Arts degree in Translation.",
      "Before joining the MFWA she was working as a freelance translator and transcriber.",
    ],
  },
  {
    slug: "michael-etrue",
    name: "Michael Etrue",
    role: "Programme Associate",
    team: "communications",
    thumb: `${U}2026/03/Untitled-design-13-570x696.png`,
    photo: `${U}2026/03/Untitled-design-13-840x976.png`,
    bio: [
      "Michael Etrue is a Programme Associate at the Media Foundation for West Africa (MFWA), where he coordinates the planning and execution of the organisation’s communications strategy, ensures the visibility of its programme areas across West Africa, and leads brand communication across its digital channels.",
      "Prior to his current role, Michael served as a coordinator for an MFWA media monitoring project. Before joining MFWA, he was the Director of Solutions at Zach Levi & Associates, a data analytics and business advisory startup, where he led business strategy, client communication, solution design, and project management.",
      "Michael previously worked as Assistant Communications Specialist on the USAID-funded Sustainable Fisheries Management Project in Ghana. He also served as Project Delivery Support (Communications) at the British Council Ghana, supporting the GIZ-funded Jobs for Youth: Migration and Employment Promotion Project and the UK Government-funded I-WORK (Improving Work Opportunities – Relaying Knowledge) Project.",
      "He has a Master of Philosophy degree in Communication Studies from the University of Ghana and a Bachelor of Science degree in Information and Communication Technology Education from the University of Education, Winneba.",
    ],
  },
  {
    slug: "miliza-fernandes-djata",
    name: "Miliza Noemi F. Djata",
    role: "Project Assistant",
    team: "programmes",
    thumb: `${U}2024/08/Miliza.png`,
    photo: `${U}2024/08/Miliza.png`,
    bio: [
      "Miliza Noemi Fernandes Djata is a Project Assistant at the Media Foundation for West Africa (MFWA), based in the organisation’s Guinea-Bissau office.",
      "She currently supports the implementation of the European Union-funded project “Promote and Protect Democracy by Safeguarding Freedom of Opinion and Expression and Combating Mis/Disinformation in Guinea-Bissau,” implemented by MFWA in partnership with Reporters Without Borders (RSF) and Fondation Hirondelle.",
      "In her role, Miliza contributes to the coordination and implementation of project activities, including organising trainings and stakeholder engagements, supporting project monitoring and documentation, coordinating with consultants and partners, and assisting in the preparation of technical and administrative reports.",
      "She has also contributed to MFWA’s broader Freedom of Expression Programme by monitoring and documenting developments related to press freedom, freedom of expression, and media rights in Guinea-Bissau.",
      "Miliza holds a Bachelor’s degree in International Relations from the Universidade Evangélica de Goiás (UniEvangélica), Brazil. She is passionate about media development, freedom of expression, and democratic governance. She is fluent in Portuguese and Crioulo, and has professional working proficiency in English and French.",
    ],
  },
  {
    slug: "nana-oduro-korankye",
    name: "Nana Oduro Korankye",
    role: "Graphic Designer",
    team: "communications",
    thumb: `${U}2026/03/Nana-Kay-2-570x696.png`,
    photo: `${U}2026/03/Nana-Kay-2-840x1177.png`,
    bio: [
      "Nana Oduro Korankye works as a graphic designer under the Institutional Development Programme. He helps tell the organization’s story by creating visual materials that make their programs and research easier to follow. From social media graphics to event banners, Nana makes sure everything looks consistent and professional so the public can stay engaged with their work.",
      "He brings a practical background from his previous roles at Brand Surge Marketing and Black Excellence House, where he helped manage brands and design event materials.",
    ],
  },
  {
    slug: "paul-kofi-gozo",
    name: "Paul Kofi Gozo",
    role: "Programme Assistant",
    team: "programmes",
    thumb: `${U}2025/07/PAUL-2-570x696.jpg`,
    photo: `${U}2025/07/PAUL-2-840x918.jpg`,
    bio: [
      "Paul Kofi Gozo is a Programme Assistant under the Media for Democracy and Good Governance Programme.",
      "Before joining the Programmes team, he worked as an investigative journalist with The Fourth Estate and as a fact-checker with Fact-Check Ghana, MFWA’s public interest journalism and factchecking projects respectively, between September 2020 and April 2023.",
      "He holds a Bachelor’s degree in Communication Studies from the University of Media, Arts and Communication–Institute of Journalism (UniMAC-IJ), where he majored in Journalism.",
      "Paul has also worked as a radio trainer and news editor and previously served as a member of the National Campaigns Committee of Amnesty International Ghana.",
    ],
  },
  {
    slug: "philip-teye-agbove",
    name: "Philip Teye Agbove",
    role: "Investigative Journalist",
    team: "journalism",
    thumb: `${U}2026/02/PHILIP-scaled-e1770377316576-570x696.png`,
    photo: `${U}2026/02/PHILIP-scaled-e1770377316576-840x930.png`,
    bio: [
      "Philip Teye Agbove is an award-winning investigative journalist focused on Indigenous peoples’ rights, accountability and human rights reporting. He uses investigative reporting and fact-checking as tools to drive justice and institutional accountability.",
      "He works with The Fourth Estate, the public interest, non-profit investigative journalism project of the Media Foundation for West Africa (MFWA), where his reporting has exposed corruption, abuse of power, environmental injustice, and threats to press freedom. His work has triggered audits, prosecutions, and, in several cases, direct relief for affected victims and communities.",
      "Before joining MFWA as a fellow in 2022, Philip worked with the Ghana News Agency and served as a correspondent for UK-based SheHub.tv, a platform dedicated to women-focused stories. He also had a stint with Radio Ada, Ghana’s premier community radio station, where he developed a strong foundation in community-centered journalism.",
      "A native of Ghana’s coastal communities in the Greater Accra Region, Philip has dedicated part of his early career to reporting on human trafficking on the Volta Lake, with a focus on amplifying the experiences of vulnerable children and marginalized groups.",
      "His work has earned him significant recognition. He is a recipient of the 2025 Konrad Adenauer Stiftung Media Award for Local Journalism and won the Best Community Reporter in West Africa at the CJID Excellence Awards 2025. Philip is also the 2023 Ghana Journalists Association Best News Journalist (Online) of the Year. He was among four journalists celebrated by the TRACE Prize for Investigative Reporting in 2025 and was shortlisted for the 2025 Amnesty International Media Awards. In 2022, he received the Most Outstanding Justice Advocate Award from International Justice Mission Ghana and was named MFWA’s Most Promising Young Investigative Journalist. He was crowned Ghana’s Outstanding Student Journalist of the Year in 2021 by the National Students Achievement Awards Ghana (NASAAG) and Ghana’s Best Student Radio Presenter in 2020 by the Ghana Student Awards, among other recognitions.",
      "Philip has reported for international outlets including BBC, CBC, IWPR, and SheHub.tv. He believes in journalism that challenges power, amplifies unheard voices, and drives meaningful social change. Beyond reporting, he mentors young journalists and holds a Diploma in Journalism and Media Studies from the Ghana Media School and a Bachelor of Arts in Development Communication.",
    ],
  },
  {
    slug: "rhoda-adwoa-bondzie",
    name: "Rhoda Adwoa Bondzie",
    role: "Programme Assistant",
    team: "programmes",
    thumb: `${U}2026/03/Untitled-6-1-570x696.jpg`,
    photo: `${U}2026/03/Untitled-6-1-840x1228.jpg`,
    bio: [
      "Rhoda Adwoa Bondzie is a Programme Assistant for FOE and Digital Rights. She joined the MFWA as a National Service Person under the Fact Checking Fellowship in 2023, and coordinated the organisation’s project on Radio Language Monitoring in 2024.",
      "She holds a Bachelor’s degree in Economics and Philosophy from the University of Ghana. She has also worked as an intern at the Audit Department under the Surveying and Mapping Division at the Lands Commission of Ghana.",
    ],
  },
  {
    slug: "richard-koduah",
    name: "Richard Koduah",
    role: "Office Assistant",
    team: "operations",
    thumb: `${U}2025/07/richard-1-scaled-e1770376899403-570x696.png`,
    photo: `${U}2025/07/richard-1-scaled-e1770376899403-840x892.png`,
    bio: [
      "Richard Koduah is the Administrative Assistant at the Media Foundation for West Africa (MFWA). He joined the organization in 1999.",
      "He has a Diploma in Business studies (DBS) from the Institute of Professional Studies. He also has a Higher National Diploma (HND) in Accountancy from the Accra Polytechnic.",
    ],
  },
  {
    slug: "seth-j-bokpe",
    name: "Seth J. Bokpe",
    role: "Associate Editor",
    team: "journalism",
    thumb: `${U}2024/08/Seth-J.jpg`,
    photo: `${U}2024/08/Seth-J.jpg`,
    bio: [
      "Seth J. Bokpe is a Senior Reporter with The Fourth Estate, the public interest and accountability investigative journalism project of the Media Foundation for West Africa (MFWA).",
      "Seth is a multiple award-winning journalist with a 10-year stint with the Graphic Communications Group, Ghana’s biggest newspaper publishing company.",
      "Before joining the MFWA, he was the News Editor of The Ghana Report, a news portal. He also earned a living with the AfricaWatch Magazine, as well as freelanced for the One World Magazine in the Netherlands.",
      "Seth holds a Bachelor of Arts degree in Communication Studies from the Ghana Institute of Journalism and a Balance Scorecard Professional Certificate from the George Washington University.",
      "He is also an Alumnus of the Bloomberg Media Initiative, Africa.",
    ],
  },
  {
    slug: "solomon-joojo-cobbinah",
    name: "Solomon Joojo Cobbinah",
    role: "Associate Editor",
    team: "journalism",
    thumb: `${U}2026/03/Untitled-5-570x696.jpg`,
    photo: `${U}2026/03/Untitled-5-840x1163.jpg`,
    bio: [
      "Solomon Joojo Cobbinah is a Ghanaian investigative journalist, storyteller, and human rights advocate. He is currently an Associate Editor at The Fourth Estate, a nonprofit, public-interest investigative journalism initiative of the Media Foundation for West Africa dedicated to promoting transparency, accountability, and democratic governance.",
      "Cobbinah has built a distinguished career documenting human rights violations and systemic injustices in Ghana. His investigations have exposed abuses in prayer camps and witch camps, as well as entrenched forms of discrimination affecting vulnerable communities. His reporting on discriminatory cultural practices that barred girls and women from crossing the River Offin during menstruation and on certain days led to a landmark petition before the African Committee of Experts on the Rights and Welfare of the Child. The Government of Ghana subsequently agreed to settle the case out of court, marking a significant step toward safeguarding the rights and dignity of affected children and women.",
      "His investigative work titled “As If We Weren’t Human”, which exposed military and police brutality, prompted the Commission on Human Rights and Administrative Justice (CHRAJ) to order compensation for victims. The investigation also formed part of the evidence presented before the ECOWAS Court of Justice, which ordered the Government of Ghana to prosecute military personnel responsible for the abuses, and fully implement the ruling of CHRAJ. This demonstrates direct institutional and legal impact of his journalism.",
      "Cobbinah’s work has earned him multiple national and international recognitions. He received the Human Rights Defenders Award from CHRAJ and won the Best Documentary award from the Ghana Journalists Association in 2022 and 2023. He is also a recipient of the Vera Chirwa Award from the Centre for Human Rights in recognition of his courageous and impactful journalism.",
      "He has worked with leading media organisations in Ghana, including TV3 Network, JoyNews, GHOne TV, and Starr FM, where he served in various roles ranging from broadcast journalist and producer to editor and Managing News Editor. His career reflects a consistent trajectory of leadership, editorial excellence, and public-interest reporting.",
      "He holds a Bachelor of Arts degree in Communication Studies and a Master of Philosophy (MPhil) in Human Rights and Democratisation in Africa from the University of Pretoria.",
      "Through his work, Cobbinah continues to advance accountability, amplify marginalised voices, and drive institutional reforms in Ghana and across Africa.",
    ],
  },
  {
    slug: "sulemana-braimah",
    name: "Sulemana Braimah",
    role: "Executive Director",
    team: "leadership",
    thumb: `${U}2025/07/3-13-570x696.png`,
    photo: `${U}2025/07/3-13-840x1076.png`,
    bio: [
      "Sulemana Braimah is the Executive Director of the Media Foundation for West Africa (MFWA). He has been leading the team at the MFWA since 2014.",
      "He has led and grown the organisation from a small team of seven to over 40 staff and established partnerships with organisations in all 16 countries of West Africa. Under his leadership, the MFWA has: obtained equivalency certification as being an equivalent of a U.S. public charity under section 501(c)(3); attained UN ECOSOC Consultative status; signed MoU to become an official civil society partner of the regional inter-governmental group, ECOWAS; and introduced West Africa’s biggest annual media conference.",
      "His innovation in leadership is reflected in the restructuring of the organisation and the introduction of innovative projects such as: The Fourth Estate, Ghana’s first non-profit, public interest investigative journalism project; Fact-Check Ghana, Ghana’s first fact-checking project; the Next Generation Investigative Journalism Fellowship (NGIJ) to empower young journalists across West Africa; the West Africa Media Excellence Awards, to recognise and promote journalism excellence.",
      "In recognition of his exceptional leadership, Sulemana was named in 2019 as a Global Eisenhower Fellow. In 2023, he was the recipient of the coveted Eisenhower Fellowships Impact Award in recognition of the extraordinary impact of The Fourth Estate non-profit investigative journalism project, which he established in 2021. And under his leadership, the MFWA was named winner of Media and Information category of the World Justice Challenge in 2024.",
      "He is also the current Secretary General of the ECOWAS Civil Society Platform on Transparency and Accountability in Governance (ECSOPTAG); a former member of the Executive Committee of the West Africa Civil Society Forum (WACSOF); member of the Steering Committee of the African Network of Free Expression organisations (AFEX). From 2011 to 2015 he served on the 13-member Governing Council of IFEX, the global network of free expression organisations based in Toronto, Canada.",
      "Sulemana previously worked for five years (2002 – 2007) with The Chronicle newspaper as a reporter and later became the paper’s News Editor. In 2009, while studying at the University of Manitoba, Canada, he was a contributing writer on media and communications issues for suite101.com.",
      "He has been a reviewer of the annual global press freedom ratings (Freedom of the Press Index) by the US-based Freedom House Inc. He has participated in and presented papers on media rights and freedom of expression issues at various national, regional and international conferences.",
      "Sulemana holds MPhil (Communication Studies – best graduating student) and Bachelor of Arts (Sociology with Philosophy – First Class Honours) both from the University of Ghana. In recognition of his academic excellence, he was awarded a Canadian Fellowship programme for studies at the University of Manitoba in Canada, as part of his MPhil studies.",
    ],
  },
  {
    slug: "thelma-dede-amedeku",
    name: "Thelma Dede Amedeku",
    role: "Investigative Journalist",
    team: "journalism",
    thumb: `${U}2026/03/Thelma-MFWA-staff-bio.png`,
    photo: `${U}2026/03/Thelma-MFWA-staff-bio.png`,
    bio: [
      "Thelma Dede Amedeku is an investigative journalist with The Fourth Estate, the MFWA’s investigative journalism project. She specialises in investigating social media trends, debunking mis/disinformation, and exposing the misuse of public funds through data-driven and open-source intelligence (OSINT) techniques.",
      "Some of her works have contributed to legislative and institutional reforms. She cut her teeth on fact-checking and investigative journalism during the Media Foundation for West Africa’s 2022 Next Generation Investigative Journalism (NGIJ) fellowship, where she was adjudged the Best Checker of the Fellowship in 2022.",
      "She continues to expand her expertise in OSINT and data analysis to strengthen evidence-based journalism in Ghana and beyond. Before joining the MFWA team, she worked as a content writer for multiple brands. Thelma is currently pursuing a Bachelor of Arts degree in Journalism at the University of Media Arts and Communication (UNIMAC).",
    ],
  },
  {
    slug: "victoria-enyonam-adonu",
    name: "Victoria Enyonam Adonu",
    role: "Programme Assistant",
    team: "programmes",
    thumb: `${U}2026/03/victoria-1-570x696.png`,
    photo: `${U}2026/03/victoria-1-840x1273.png`,
    bio: [
      "Victoria Enyonam Adonu is a Program Assistant with the Freedom of Expression and Digital Rights program where she supports the MFWA’s work on internet freedom, digital rights policy, freedom of expression, journalist safety, and gender digital equity across West Africa through research, advocacy, and stakeholder engagement.",
      "Before transitioning to this role, Victoria worked as an investigative journalist with The Fourth Estate and a researcher and writer with Fact-Check Ghana, MFWA’s investigative journalism and fact checking projects respectively. She is a product of the Media Foundation for West Africa’s second cohort of the Next Generation of Investigative Journalism Fellowship (2022).",
      "Before joining the Media Foundation for West Africa, Victoria worked as a ghostwriter and book editor with Buabeng Books Limited in Accra Ghana, and as a broadcast journalist with ATL FM for her national service. She has a Bachelor of Arts degree in Communication Studies from the University of Cape Coast.",
    ],
  },
  {
    slug: "vivian-affoah",
    name: "Vivian Affoah",
    role: "Senior Programme Manager",
    team: "programmes",
    thumb: `${U}2025/07/Untitled-design-14-570x696.png`,
    photo: `${U}2025/07/Untitled-design-14-840x976.png`,
    bio: [
      "Vivian Affoah is the Senior Programme Manager for Freedom of Expression and Digital Rights at the Media Foundation for West Africa (MFWA). She has over 17 years of experience in coordinating multi-country projects focused on media development, the safety of journalists, and digital rights advocacy across the sub-region.",
      "Vivian joined the MFWA in 2009 and has since risen through progressively senior roles, including leading the organisation’s communication and outreach efforts. In her current role, she oversees the strategic implementation of the MFWA’s Freedom of Expression and Digital Rights programme.",
      "Throughout her career with the organisation, Ms. Affoah has played a central role in the MFWA’s research efforts, coordinating the production and dissemination of critical reports on the state of freedom of expression and media violations. She has also been instrumental in expanding the organisation’s footprint in internet freedom and governance advocacy while strengthening collaborative ties with national partners across West Africa.",
      "Before joining the MFWA, Vivian worked as a reporter for The Mail newspaper in Ghana, where she covered social issues. She holds a Bachelor of Arts degree from the Ghana Institute of Journalism (GIJ), now the University of Media, Arts and Communication (UniMAC-IJ).",
    ],
  },
  {
    slug: "william-nlanjerbor-jalulah",
    name: "William Nlanjerbor Jalulah",
    role: "Associate Editor",
    team: "journalism",
    thumb: `${U}2026/03/Jallulah-570x696.jpg`,
    photo: `${U}2026/03/Jallulah-840x1181.jpg`,
    bio: [
      "William Nlanjerbor Jalulah is an Associate Editor with The Fourth Estate, a public interest and accountability investigative journalism project of the Media Foundation for West Africa (MFWA). Before joining The Fourth Estate, he worked as a Programme Officer of Media for Democracy and Good Governance Programme (MDGG) of the MFWA.",
      "He brings many years of experience in media management. Prior to joining the MFWA, William served as General Manager of A1 Radio in Bolgatanga, after serving as the company’s Managing Editor for close to a decade. He also worked with The Chronicle newspaper, Metro TV and Class FM as Upper East Regional Correspondent. He also taught English Language at the Bolgatanga Technical Institute. William also taught Media Studies and Journalism on part-time basis at the Bolgatanga Technical University.",
      "He holds a Bachelor of Arts Degree in Management and Sociology (Combined Major) from the University of Ghana, Legon, and Master’s Degree in English Language, specialising in Teaching English as a Second Language (TESL) from the University of Education, Winneba. He has recently submitted his thesis and awaits graduation with a Master of Philosophy (MPhil) in Journalism and Media Studies from the University of Education, Winneba.",
    ],
  },
];
